[env:roomiq]
platform         = espressif32
board            = esp32-c6-devkitm-1
framework        = arduino
monitor_speed    = 115200
upload_speed     = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    adafruit/Adafruit SHT4x Library @ ^1.0.4
    sensirion/Sensirion I2C SCD4x  @ ^0.4.0
    Wire
    DNSServer
    WebServer
